development:
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: mouth_development
  
test:
  adapter: mysql
  host: localhost
  username: root
  password: 
  database: mouth_test
